export const refs = {
  dayOfWeekRef: document.querySelector('.js-dayOfWeek'),
  monthAndDateRef: document.querySelector('.js-monthAndDate'),
  searchFormRef: document.querySelector('#search-form'),
  mainWeatherNow: document.querySelector('.weathernowbg'),
  weatherNowCityRef: document.querySelector('.js-weathernow-city'),
  weathernowTempRef: document.querySelector('.weathernow-temp'),
  weathernowSkyRef: document.querySelector('.weathernow-sky'),
  windValueNowRef: document.querySelector('.js-windValueNow'),
  humidityValueNow: document.querySelector('.js-humidityValueNow'),
  pressureValueNow: document.querySelector('.js-pressureValueNow'),
  spinnerRef: document.querySelector('.loader'),
  blurRef: document.querySelectorAll('.js-blur'),
  searchSectionRef: document.querySelector('.search'),
  wperDayRef: document.querySelector('.wper-day'),
  weatherWeekRef: document.querySelector('.week'),
  notifyRef: document.querySelector('.notify'),
  byTimeHours: document.querySelectorAll('.by-time_hours'),
  byTimeTemp: document.querySelectorAll('.by-time_temp'),
  byTimeIcon: document.querySelectorAll('.by-time_icon'),
  weatherWeekWeekday: document.querySelectorAll('.weather-week-weekday'),
  jsTomorrowDay: document.querySelector('.js-tomorrow-day'),
  weatherWeekWeekdate: document.querySelectorAll('.weather-week-weekdate'),
  jsWeekValueMin: document.querySelectorAll('.js-week-value-min'),
  weatherWeekSquare: document.querySelectorAll('.weather-week-square'),
  //
  jsNightDataTemp: document.querySelector('.wper-day-item__temp'),
  jsNightDataFeels: document.querySelector('.wper-day-item__feelstemp'),
  jsNightDataMps: document.querySelector('.wper-day-item__datamps'),
  jsNightDataHummid: document.querySelector('.wper-day-item__datahumid'),
  jsNightDataPressure: document.querySelector('.wper-day-item__datapressure'),
  //
  jsMorningDataTemp: document.querySelector('.js-morning-data-temp'),
  jsMorningDataFeels: document.querySelector('.js-morning-data-feels'),
  jsMorningDataMps: document.querySelector('.js-morning-data-mps'),
  jsMorningDataHummid: document.querySelector('.js-morning-data-hummid'),
  jsMorningDataPressure: document.querySelector('.js-morning-data-pressure'),
  ///
  jsDayDataTemp: document.querySelector('.js-day-data-temp'),
  jsDayDataFeels: document.querySelector('.js-day-data-feels'),
  jsDayDataMps: document.querySelector('.js-day-data-mps'),
  jsDayDataHummid: document.querySelector('.js-day-data-hummid'),
  jsDayDataPressure: document.querySelector('.js-day-data-pressure'),
  //
  jsEveningDataTemp: document.querySelector('.js-evening-data-temp'),
  jsEveningDataFeels: document.querySelector('.js-evening-data-feels'),
  jsEveningDataMps: document.querySelector('.js-evening-data-mps'),
  jsEveningDataHummid: document.querySelector('.js-evening-data-hummid'),
  jsEveningDataPressure: document.querySelector('.js-evening-data-pressure'),
  mainIcon: document.querySelector('.sunny_icon'),
  //
  jsWeekIcon: document.querySelectorAll('.js-week-icon'),
  //
  jsIconNight: document.querySelector('.js-icon-night'),
  jsIconMorning: document.querySelector('.js-icon-morning'),
  jsIconEvening: document.querySelector('.js-icon-evening'),
  jsIconDay: document.querySelector('.js-icon-day'),
  snow: document.querySelector('.snow'),
};
