export const refs = {
  dayOfWeekRef: document.querySelector('.js-dayOfWeek'),
  monthAndDateRef: document.querySelector('.js-monthAndDate'),
  searchFormRef: document.querySelector('#search-form'),
  weatherNowCityRef: document.querySelector('.js-weathernow-city'),
  weathernowTempRef: document.querySelector('.weathernow-temp'),
  weathernowSkyRef: document.querySelector('.weathernow-sky'),
  windValueNowRef: document.querySelector('.js-windValueNow'),
  humidityValueNow: document.querySelector('.js-humidityValueNow'),
  pressureValueNow: document.querySelector('.js-pressureValueNow'),
  spinnerRef: document.querySelector('.loader'),
  blurRef: document.querySelectorAll('.js-blur'),
  searchSectionRef: document.querySelector('.search'),
  wperDayRef: document.querySelector('.wper-day'),
  weatherWeekRef: document.querySelector('.week'),
  notifyRef: document.querySelector('.notify'),
  byTimeHours: document.querySelectorAll('.by-time_hours'),
  byTimeTemp: document.querySelectorAll('.by-time_temp'),
  weatherWeekWeekday: document.querySelectorAll('.weather-week-weekday'),
  jsTomorrowDay: document.querySelector('.js-tomorrow-day'),
  weatherWeekWeekdate: document.querySelectorAll('.weather-week-weekdate'),
  jsWeekValueMin: document.querySelectorAll('.js-week-value-min'),
};
